"use client";
import Image from "next/image";
import { useState } from "react";
import { Bot, Send, Sparkles } from "lucide-react";
import type { Property } from "@/lib/types";

type Message={role:"user"|"assistant";text:string;matches?:Array<Property&{matchReasons:string[]}>};
export function ChatExperience(){
  const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Hi! Tell me what kind of property you’re looking for. For example: “A 2-bedroom apartment in Hamra under $1,500 with parking.”"}]);
  const [input,setInput]=useState(""); const [loading,setLoading]=useState(false); const [showLead,setShowLead]=useState(false);
  async function send(e:React.FormEvent){e.preventDefault();if(!input.trim()||loading)return;const text=input.trim();setMessages(v=>[...v,{role:"user",text}]);setInput("");setLoading(true);try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});const data=await res.json();setMessages(v=>[...v,{role:"assistant",text:data.reply||data.error,matches:data.matches}]);}catch{setMessages(v=>[...v,{role:"assistant",text:"Something went wrong. Please try again."}]);}finally{setLoading(false)}}
  return <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><section className="card flex min-h-[580px] flex-col overflow-hidden"><div className="flex items-center gap-3 border-b border-ink/10 p-5"><span className="rounded-full bg-lime p-2 text-sage"><Bot size={20}/></span><div><p className="font-bold">Realtors X Assistant</p><p className="text-xs text-sage">Searching live listings</p></div></div><div className="flex-1 space-y-5 overflow-y-auto p-5 md:p-7">{messages.map((m,i)=><div key={i} className={m.role==="user"?"ml-auto max-w-[80%]":"max-w-[95%]"}><div className={m.role==="user"?"rounded-2xl rounded-br-sm bg-sage p-4 text-sm text-white":"rounded-2xl rounded-bl-sm bg-cream p-4 text-sm"}>{m.text}</div>{m.matches&&<div className="mt-4 grid gap-3 sm:grid-cols-2">{m.matches.map(p=><PropertyResult key={p.id} property={p}/>)}</div>}</div>)}{loading&&<div className="w-fit animate-pulse rounded-2xl bg-cream p-4 text-sm">Searching your options…</div>}</div><form onSubmit={send} className="flex gap-3 border-t border-ink/10 p-4"><input className="field flex-1" value={input} onChange={e=>setInput(e.target.value)} placeholder="A 3-bedroom house near…"/><button className="btn !px-4" aria-label="Send" disabled={loading}><Send size={18}/></button></form></section><aside className="space-y-4"><div className="rounded-3xl bg-ink p-6 text-white"><Sparkles className="text-sage"/><h2 className="mt-5 text-2xl font-bold">Want a human eye?</h2><p className="mt-2 text-sm leading-6 text-white/70">Leave your preferences and an agent can follow up with options tailored to you.</p><button onClick={()=>setShowLead(true)} className="mt-5 w-full rounded-full bg-sage px-5 py-3 text-sm font-bold text-white transition hover:bg-[#0874b7]">Request a call</button></div><div className="card p-5 text-sm text-ink/55"><b className="text-ink">Search tips</b><p className="mt-2 leading-6">Include your max budget, preferred area, number of bedrooms, property type, and features like parking or a balcony.</p></div></aside>{showLead&&<LeadModal onClose={()=>setShowLead(false)}/>}</div>;
}
function PropertyResult({property:p}:{property:Property&{matchReasons:string[]}}){return <article className="overflow-hidden rounded-2xl border border-ink/10 bg-white">{p.images?.[0]&&<div className="relative aspect-[16/9]"><Image src={p.images[0]} alt={`${p.title} property image`} fill unoptimized className="object-cover"/></div>}<div className="p-4"><div className="flex justify-between gap-2"><span className="text-xs font-bold uppercase text-sage">{p.type}</span><b>${Number(p.price).toLocaleString()}</b></div><h3 className="mt-2 font-bold">{p.title}</h3><p className="mt-1 text-xs text-ink/50">{p.location} · {p.bedrooms} bd · {p.bathrooms} ba · {Number(p.size).toLocaleString()} sq ft</p>{p.matchReasons.length>0&&<p className="mt-3 text-xs text-sage">Matches: {p.matchReasons.join(", ")}</p>}<p className="mt-3 line-clamp-2 text-xs leading-5 text-ink/60">{p.description}</p></div></article>}
function LeadModal({onClose}:{onClose:()=>void}){const [done,setDone]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget));const res=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const json=await res.json();setBusy(false);if(res.ok)setDone(true);else setError(json.error)}return <div className="fixed inset-0 z-50 overflow-y-auto bg-ink/50 p-4 backdrop-blur-sm"><div className="mx-auto my-8 max-w-lg rounded-3xl bg-cream p-7">{done?<div className="py-10 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-lime text-2xl">✓</div><h2 className="mt-5 text-2xl font-black">You’re all set</h2><p className="mt-2 text-ink/55">An agent will be in touch with matching options.</p><button onClick={onClose} className="btn mt-6">Back to search</button></div>:<form onSubmit={submit}><div className="flex justify-between"><div><p className="text-sm font-semibold text-sage">Agent follow-up</p><h2 className="text-2xl font-black">Tell us about you</h2></div><button type="button" onClick={onClose}>✕</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><LeadField label="Name"><input className="field" name="name" required/></LeadField><LeadField label="Phone"><input className="field" name="phone" type="tel" required/></LeadField><LeadField label="Budget"><input className="field" name="budget" type="number" min="0" required/></LeadField><LeadField label="Preferred area"><input className="field" name="preferred_area" required/></LeadField><LeadField label="Property type"><select className="field" name="requested_property_type" required><option value="">Choose one</option><option>apartment</option><option>house</option><option>villa</option><option>townhouse</option><option>studio</option><option>office</option><option>land</option></select></LeadField><LeadField label="Move-in date"><input className="field" name="move_in_date" type="date"/></LeadField></div>{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}<button className="btn mt-6 w-full" disabled={busy}>{busy?"Sending…":"Request a call"}</button></form>}</div></div>}
function LeadField({label,children}:{label:string,children:React.ReactNode}){return <label className="text-sm font-semibold"><span className="mb-2 block">{label}</span>{children}</label>}
